**What is NumPy?**

**NumPy is a Python library used for working with arrays.**

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

**NumPy stands for Numerical Python.**

**Python stores data in several diffrent ways. The most popular ways are List and Dictionaries. & Numpy array is also a datastructure used to store the data.**

**Nympy arrays are similar to Lists**

**Why Use NumPy?**

**In Python we have lists that serve the purpose of arrays, but they are slow to process.**

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

**The array object in NumPy is called ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

**Why is NumPy Faster Than Lists?**

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



**Similarities between List and Numpy array**

- Both are used to store the data.

- Both are "Mutable" i.e. we can add or remove any element from it.

- Both can be indexed & iterated through we can access the values through indexes.

- Both can be sliced. We can perform slicing operation on both.

**Diffrence between List and Numpy array**

**List** :- It is used to store data of diffrent types. [1, 2.1, "a", 1]
 
**Array** :- It is used to store data of similar types. [1, 2, 3, 4]

Operations that we can perform on them :- for e.g.

**You can apply division operation on an array but not on lists.**

In [ ]:
import numpy as np
a=np.array([3,6,9,12])
a/3

array([1., 2., 3., 4.])

In [ ]:
list1 = [2,4,6,8,10]
list1/2

TypeError: ignored

**Which Language is NumPy written in?**

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

**To Install NumPy**

Before using the numpy library we need to install it.

In [ ]:
pip install numpy

**Import NumPy**

Once NumPy is installed, import it in your applications by adding the import keyword:

In [ ]:
import numpy

#Now NumPy is imported and ready to use.

**Example**

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**NumPy as np**

NumPy is usually imported under the np alias.



**Now the NumPy package can be referred to as np instead of numpy**

**Example**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**Checking NumPy Version**

The version string is stored under version attribute.

In [ ]:
import numpy as np

print(np.__version__)

1.19.5


**To upgrade NumPy**

In [ ]:
pip install numpy --upgrade

     |████████████████████████████████| 15.3MB 251kB/s 
ERROR: tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.20.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5


**NumPy Ndarray**

Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing. Each element of the Array object contains the same size in the memory.

**Creating a ndarray object**

The ndarray object can be created by using the array routine of the numpy module.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

**To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:**

**Example**

Use a tuple to create a NumPy array:

In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


**Dimensions in Arrays**

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

**0-D Arrays**

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

**Example**

Create a 0-D array with value 42

In [ ]:
import numpy as np

arr = np.array(42)

print(arr)

42


**1-D Arrays**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.



**Example**

Create a 1-D array containing the values 1,2,3,4,5

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**2-D Arrays An array that has 1-D arrays as its elements is called a 2-D array.**

These are often used to represent matrix or 2nd order tensors.

**Example**

Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


**3-D arrays**

**An array that has 2-D arrays (matrices) as its elements is called 3-D array.**

**Example**

Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Check Number of Dimensions?**

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

**Example**

Check how many dimensions the arrays have:

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


**Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

**Example**

Create an array with 5 dimensions and verify that it has 5 dimensions:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


**NumPy Array Indexing**

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

**Example**

Get the first element from the following array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


**Example**

Get the second element from the following array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


**Example**

Get third and fourth elements from the following array and add them.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


**Access 2-D Arrays**

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

**Example**

Access the 2nd element on 1st dim:
Access the 4th element on 2nd dim:

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])
print('4th element on 12nd dim: ', arr[1,3])

2nd element on 1st dim:  2
4th element on 12nd dim:  9


**Access 3-D Arrays**

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

**Example**

Access the third element of the second array of the first array:

**Example**

Access the third element of the second array of the first array:

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Example Explained arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays: [[1, 2, 3], [4, 5, 6]] and: [[7, 8, 9], [10, 11, 12]] Since we selected 0, we are left with the first array: [[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays: [1, 2, 3] and: [4, 5, 6] Since we selected 1, we are left with the second array: [4, 5, 6]

The third number represents the third dimension, which contains three values: 4 5 6 Since we selected 2, we end up with the third value: 6

**Negative Indexing**

Use negative indexing to access an array from the end.

**Example**

Print the last element from the 2nd dim:

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


**NumPy Array Slicing**

Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

**Example**

Slice elements from index 1 to index 5 from the following array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


**Example**

Slice elements from index 4 to the end of the array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


**Example**

 Slice elements from the beginning to index 4 (not included):

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


**Negative Slicing**

Use the minus operator to refer to an index from the end:

**Example**

Slice from the index 3 from the end to index 1 from the end:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:6:3])

[1 4]


**Example**

Return every other element from the entire array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


**Slicing 2-D Arrays**

**Example**

From the second element, slice elements from index 1 to index 4 (not included):

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
#Note: Remember that second element has index 1.

[7 8 9]


**Example**

From both elements, return index 2:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


**Example**

From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**NumPy Data Types**

**Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer b - boolean u - unsigned integer f - float c - complex float m - timedelta M - datetime O - object S - string U - unicode string V - fixed chunk of memory for other type ( void )

**Checking the Data Type of an Array**

The NumPy array object has a property called dtype that returns the data type of the array:

**Example**

Get the data type of an array object:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


**Example**

Get the data type of an array containing strings:

In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


**Creating Arrays With a Defined Data Type**

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

**Example**

Create an array with data type string:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


**Converting Data Type on Existing Arrays**

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

**Example**

Change data type from float to integer by using 'i' as parameter value:

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


**NumPy Array Copy vs View**

**The Difference Between Copy and View**

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

**COPY:**

**Example**

Make a copy, change the original array, and display both arrays:



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**The copy SHOULD NOT be affected by the changes made to the original array.**

**VIEW:**

**Example**

Make a view, change the original array, and display both arrays:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


**The view SHOULD be affected by the changes made to the original array.**

**NumPy Array Shape**

**Shape of an Array**

**The shape of an array is the number of elements in each dimension.**



**Get the Shape of an Array**

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

**Example**

**Print the shape of a 2-D array:**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


**NumPy Array Iterating**

**Iterating Arrays**

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

**Example**

Iterate on the elements of the following 1-D array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


**Iterating 2-D Arrays**

In a 2-D array it will go through all the rows.

**Example**

Iterate on the elements of the following 2-D array:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


If we iterate on a n-D array it will go through n-1th dimension one by one.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

**Example**

Iterate on each scalar element of the 2-D array:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


**Iterating 3-D Arrays**

In a 3-D array it will go through all the 2-D arrays.

**Example**

Iterate on the elements of the following 3-D array:

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


**Iterating Arrays Using nditer()**

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

**Example**

Iterate through the following 3-D array:

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**NumPy Joining Array**

Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

Example Join two arrays




In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


**Split Into Arrays**

The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

**Example**

Access the splitted arrays:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr[0])
print(newarr[1])


[1 2 3]
[4 5 6]


**Splitting 2-D Arrays**

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

**Example**

Split the 2-D array into three 2-D arrays.

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 2)

print(newarr)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


**NumPy Searching Arrays**

Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

**Example**

Find the indexes where the value is 4:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


The example above will return a tuple: (array([3, 5, 6],)

Which means that the value 4 is present at index 3, 5, and 6.

**Example**

Find the indexes where the values are even:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


**Example**

Find the indexes where the values are odd

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


**NumPy Sorting Arrays**

**Sorting Arrays**

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

**Example**

Sort the array:

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


**Example**

Sort the array alphabetically:

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


**Sorting a 2-D Array**

If you use the sort() method on a 2-D array, both arrays will be sorted:

**Example**

Sort a 2-D array:

In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


**Random Numbers in NumPy**

What is a Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Pseudo Random and True Random.

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

Generate Random Number

NumPy offers the random module to work with random numbers.

Example

Generate a random integer from 0 to 100:

In [ ]:
from numpy import random

x = random.randint(100)

print(x)

85


**Generate Random Float**

The random module's rand() method returns a random float between 0 and 1.

**Example**

Generate a random float from 0 to 1:

In [ ]:
from numpy import random

x = random.rand()

print(x)

0.6837929575312485


**Generate Random Array**

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

**Integers**

The randint() method takes a size parameter where you can specify the shape of an array.

**Example**

Generate a 1-D array containing 5 random integers from 0 to 100:

In [ ]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[57 16 56 96 52]


**Example**

Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [ ]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[15 55 67 86 10]
 [66 99 23 53 89]
 [93 83 80 79  2]]


**Floats**

The rand() method also allows you to specify the shape of the array.

**Example**

Generate a 1-D array containing 5 random floats:

In [ ]:
from numpy import random

x = random.rand(5)

print(x)

[0.23505332 0.60161181 0.63605877 0.87215471 0.52624018]


**Example**

Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [ ]:
from numpy import random

x = random.rand(2,3)

print(x)

[[0.08978719 0.91323319 0.12528539]
 [0.04130851 0.89647978 0.30222351]]


**Generate Random Number From Array**

The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

**Example**

Return one of the values in an array:

In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

3


The choice() method also allows you to return an array of values.

Add a size parameter to specify the shape of the array.

**Example**

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):



In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 9 7 3]
 [7 7 5 9 7]
 [9 7 9 9 9]]
